SELECT
    XMLElement("Modelo_Aplicacion_LADMCOL_RIC_V0_1.RIC.RIC_CaracteristicasUnidadConstruccion", XMLAttributes(sys_guid() as "TID"),
        XMLElement("id", u.id),
        XMLElement("Identificador", u.unidad),
        XMLElement(
            "Tipo_Construccion", INITCAP(
                LOWER(CASE u.tipo_construccion WHEN 'NO CONVENCIONAL' THEN 'NO_CONVENCIONAL' ELSE u.tipo_construccion END)
            )
        ),
        XMLElement(
            "Tipo_Dominio", INITCAP(
                LOWER(
                    DECODE(
                        u.tipo_dominio,
                        'Común', 'comun',
                        u.tipo_dominio
                    )
                )
            )
        ),
        XMLElement("Tipo_Unidad_Construccion", INITCAP(LOWER(u.tipo_calificacion))), -- PENDIENTE POR HOMOLOGACION
        XMLElement("Total_Habitaciones", u.total_habitaciones),
        XMLElement("Total_Banios", u.total_banios),
        XMLElement("Total_Locales", u.total_locales),
        XMLElement("Total_Plantas", u.total_pisos_construccion),
        XMLElement(
            "Uso", DECODE(
                DECODE(
                    u.uso_id, 
                    '0', ' ',
                    '1', ' ',
                    '2', '122',
                    '3', '537',
                    '4', '526',
                    '5', '523',
                    '6', '519',
                    '7', '311',
                    '8', '313',
                    '9', '539',
                    '10', '540',
                    '11', '512',
                    '12', '416',
                    '13', '412',
                    '14', '117',
                    '15', '213',
                    '16', '211',
                    '17', '213',
                    '18', '538',
                    '19', '415',
                    '20', '536',
                    '21', '528',
                    '22', '213',
                    '23', '511',
                    '24', '213',
                    '25', '221',
                    '26', '522',
                    '27', '115',
                    '28', '216',
                    '29', '421',
                    '30', '213',
                    '31', '220',
                    '32', '213',
                    '33', '215',
                    '34', '222',
                    '35', '113',
                    '36', '231',
                    '37', '228',
                    '38', '428',
                    '39', '226',
                    '40', '114',
                    '41', '431',
                    '42', '411',
                    '43', '417',
                    '44', '414',
                    '45', '315',
                    '46', '424',
                    '47', '543',
                    '48', '531',
                    '49', '524',
                    '50', '427',
                    '51', '413',
                    '52', '425',
                    '53', '121',
                    '54', '217',
                    '55', '223',
                    '56', '112',
                    '57', '214',
                    '58', '213',
                    '59', '214',
                    '60', '515',
                    '61', ' ',
                    '62', '541',
                    '63', '124',
                    '64', '513',
                    '65', '420',
                    '66', '532',
                    '67', '214',
                    '68', '214',
                    '69', '214',
                    '70', '123',
                    '71', '111',
                    '72', '125',
                    '73', '312',
                    '74', '212',
                    '75', '218',
                    '76', '214',
                    '77', '224',
                    '78', '227',
                    '79', '118',
                    '80', '314',
                    '81', '214',
                    '82', '530',
                    '83', '529',
                    '84', '545',
                    '85', '516',
                    '86', '234',
                    '87', '422',
                    '88', '232',
                    '89', '219',
                    '90', '230',
                    '91', '418',
                    '92', ' ',
                    '93', '214',
                    '94', '214',
                    '95', '214',
                    '96', '214',
                    '97', '214',
                    '98', '214',
                    '99', '518'
                ),
            '111', 'Residencial.Apartamentos_4_y_mas_pisos_en_PH',
            '112', 'Residencial.Apartamentos_En_Edificio_4_y_5_Pisos_Cartagena',
            '113', 'Residencial.Apartamentos_Mas_De_4_Pisos',
            '114', 'Residencial.Barracas',
            '115', 'Residencial.Casa_Elbas',
            '116', 'Residencial.Depositos_Lockers',
            '117', 'Residencial.Garajes_Cubiertos',
            '118', 'Residencial.Garajes_En_PH',
            '119', 'Residencial.Salon_Comunal',
            '120', 'Residencial.Secadero_Ropa',
            '121', 'Residencial.Vivienda_Colonial',
            '122', 'Residencial.Vivienda_Hasta_3_Pisos',
            '123', 'Residencial.Vivienda_Hasta_3_Pisos_En_PH',
            '124', 'Residencial.Vivienda_Recreacional',
            '125', 'Residencial.Vivienda_Recreacional_En_PH',
            '211', 'Comercial.Bodegas_Comerciales_Grandes_Almacenes',
            '212', 'Comercial.Bodegas_Comerciales_en_PH',
            '213', 'Comercial.Centros_Comerciales',
            '214', 'Comercial.Centros_Comerciales_en_PH',
            '215', 'Comercial.Clubes_Casinos',
            '216', 'Comercial.Comercio',
            '217', 'Comercial.Comercio_Colonial',
            '218', 'Comercial.Comercio_en_PH',
            '219', 'Comercial.Hotel_Colonial',
            '220', 'Comercial.Hoteles',
            '221', 'Comercial.Hoteles_en_PH',
            '222', 'Comercial.Oficinas_Consultorios',
            '223', 'Comercial.Oficinas_Consultorios_Coloniales',
            '224', 'Comercial.Oficinas_Consultorios_en_PH',
            '225', 'Comercial.Parque_Diversiones',
            '226', 'Comercial.Parqueaderos',
            '227', 'Comercial.Parqueaderos_en_PH',
            '228', 'Comercial.Pensiones_y_Residencias',
            '229', 'Comercial.Plaza_Mercado',
            '230', 'Comercial.Restaurante_Colonial',
            '231', 'Comercial.Restaurantes',
            '232', 'Comercial.Restaurantes_en_PH',
            '233', 'Comercial.Teatro_Cinemas',
            '234', 'Comercial.Teatro_Cinemas_en_PH',
            '311', 'Industrial.Bodega_Casa_Bomba',
            '312', 'Industrial.Bodegas_Casa_Bomba_en_PH',
            '313', 'Industrial.Industrias',
            '314', 'Industrial.Industrias_en_PH',
            '315', 'Industrial.Talleres',
            '411', 'Institucional.Aulas_de_Clases',
            '412', 'Institucional.Biblioteca',
            '413', 'Institucional.Carceles',
            '414', 'Institucional.Casas_de_Culto',
            '415', 'Institucional.Clinicas_Hospitales_Centros_Medicos',
            '416', 'Institucional.Colegio_y_Universidades',
            '417', 'Institucional.Coliseos',
            '418', 'Institucional.Entidad_Educativa_Colonial_Colegio_Colonial',
            '419', 'Institucional.Estadios',
            '420', 'Institucional.Fuertes_y_Castillos',
            '421', 'Institucional.Iglesia',
            '422', 'Institucional.Iglesia_en_PH',
            '423', 'Institucional.Instalaciones_Militares',
            '424', 'Institucional.Jardin_Infantil_en_Casa',
            '425', 'Institucional.Parque_Cementerio',
            '426', 'Institucional.Planetario',
            '427', 'Institucional.Plaza_de_Toros',
            '428', 'Institucional.Puestos_de_Salud',
            '429', 'Institucional.Museos',
            '430', 'Institucional.Seminarios_Conventos',
            '431', 'Institucional.Teatro',
            '432', 'Institucional.Unidad_Deportiva',
            '433', 'Institucional.Velodromo_Patinodromo',
            '511', 'Anexo.Albercas_Banaderas',
            '512', 'Anexo.Beneficiaderos',
            '513', 'Anexo.Camaroneras',
            '514', 'Anexo.Canchas',
            '515', 'Anexo.Canchas_de_Tenis',
            '516', 'Anexo.Carretera',
            '517', 'Anexo.Cerramiento',
            '518', 'Anexo.Cimientos_Estructura_Muros_y_Placa_Base',
            '519', 'Anexo.Cocheras_Marraneras_Porquerizas',
            '520', 'Anexo.Construccion_en_Membrana_Arquitectonica',
            '521', 'Anexo.Contenedor',
            '522', 'Anexo.Corrales',
            '523', 'Anexo.Establos_Pesebreras_Caballerizas',
            '524', 'Anexo.Estacion_Bombeo',
            '525', 'Anexo.Estacion_Sistema_Transporte',
            '526', 'Anexo.Galpones_Gallineros',
            '527', 'Anexo.Hangar',
            '528', 'Anexo.Kioscos',
            '529', 'Anexo.Lagunas_de_Oxidacion',
            '530', 'Anexo.Marquesinas_Patios_Cubiertos',
            '531', 'Anexo.Muelles',
            '532', 'Anexo.Murallas',
            '533', 'Anexo.Pergolas',
            '534', 'Anexo.Piscinas',
            '535', 'Anexo.Pista_Aeropuerto',
            '536', 'Anexo.Pozos',
            '537', 'Anexo.Ramadas_Cobertizos_Caneyes',
            '538', 'Anexo.Secaderos',
            '539', 'Anexo.Silos',
            '540', 'Anexo.Tanques',
            '541', 'Anexo.Toboganes',
            '542', 'Anexo.Torre_de_Control',
            '543', 'Anexo.Torres_de_Enfriamiento',
            '544', 'Anexo.Unidad_Predial_por_Construir',
            '545', 'Anexo.Via_Ferrea'
            )
        ),
        XMLElement("Anio_Construccion", u.anio_construccion),
        XMLElement("Area_Construida", u.area_construida),
        XMLElement("Observaciones", u.observaciones),
        XMLElement("Espacio_De_Nombres", 'RIC_CARACTERISTICASUNIDADCONSTRUCCION'),
        XMLElement("Numero_Predial", p.numero_predial),
        XMLElement("predio_id", p.id)
    )
FROM unidad_construccion u
JOIN predio p ON u.predio_id = p.id
WHERE p.municipio_codigo = :municipio_codigo AND (u.numero_mezanines >= 0 AND u.numero_mezanines < 100)
AND REGEXP_LIKE(SUBSTR(p.numero_predial, 6, 2), '[0-9]')
AND p.tipo NOT IN (' ', 'A', 'C', 'D', 'F', 'G', 'H', 'M', 'N', 'I', 'V') AND (p.avaluo_catastral IS NOT NULL OR p.avaluo_catastral >= 0)
AND p.nupre NOT IN (
	SELECT nupre_repetido FROM (
		SELECT nupre AS nupre_repetido, count(nupre) AS contar_nupre FROM predio WHERE municipio_codigo = :municipio_codigo GROUP BY nupre
	) WHERE contar_nupre > 1
)
AND (p.nupre IS NOT NULL OR p.nupre != '')
AND p.id IN (
    SELECT pp.predio_id FROM persona_predio pp WHERE pp.persona_id IN (
        SELECT ps.id FROM persona ps WHERE ps.TIPO_IDENTIFICACION IN ('CC', 'CE', 'NIT', 'TI', 'RC', 'P')
    )
)
AND p.id IN(
    SELECT
        P.ID
    FROM PREDIO P
        INNER JOIN PERSONA_PREDIO PP ON (P.MUNICIPIO_CODIGO = :municipio_codigo AND PP.PREDIO_ID = P.ID) 
        INNER JOIN PERSONA_PREDIO_PROPIEDAD PPP ON PPP.PERSONA_PREDIO_ID = PP.ID    
    GROUP BY
        P.ID
){in_clause}